### ISSUE TITLE
시뮬레이션 코드 작성

### ISSUE THREAD

**Issue by ANGHOOO** [UpstageAI-git-team6/team6_100_prisoners_problem#5]
## Description

죄수들이 자신의 번호를 찾을 때 까지 시뮬레이션 하는 코드 작성

## Tasks

- [ ] 죄수번호에 따른 서랍장 선택 코드 작성
- [ ] 50개의 서랍을 여는 조건 하에서 자신의 번호를 찾았는지 못 찾았는지에 대한 코드 작성
- [ ] 성공 횟수를 세고 출력하는 코드 작성
